const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Sólido: 0},
	{Centro: 0},
	{Esquerda: 0},
	{Direita: 0},
	{Ldireita: 0},
	{Lesquerda: 0},
	{Preenchimento: 0},
	{CantoEsquerdo: 0},
	{Baixo: 0},
	{cantodireito: 0},
	{Sprite: 0},
	{Senóide: 0},
	{Senóide2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite17: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{FIM: 0},
	{Sprite23: 0},
	{FonteDeSprites: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Limbo: 0},
	{Teclado: 0},
	{Sprite5: 0},
	{Direcao: 0},
	{Platform: 0},
	{Solid: 0},
	{Porco_Patrulheiro: 0},
	{Sensor_Patrulheiro_Direita: 0},
	{Sensor_Patrulheiro_Esquerda: 0},
	{Text: 0},
	{Button: 0},
	{Browser: 0},
	{Audio: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	Centro: class extends self.ISpriteInstance {},
	Esquerda: class extends self.ISpriteInstance {},
	Direita: class extends self.ISpriteInstance {},
	Ldireita: class extends self.ISpriteInstance {},
	Lesquerda: class extends self.ISpriteInstance {},
	Preenchimento: class extends self.ISpriteInstance {},
	CantoEsquerdo: class extends self.ISpriteInstance {},
	Baixo: class extends self.ISpriteInstance {},
	cantodireito: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	FIM: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Limbo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Porco_Patrulheiro: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Direita: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Esquerda: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {}
}